import { User, Task, Project, Team, CalendarEvent, AnalyticsData } from './types';

export const currentUser: User = {
  id: '1',
  name: 'Mark Johnson',
  email: 'mark@example.com',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
  role: 'Project Manager',
  department: 'Development',
  jobTitle: 'Product Manager',
  phone: '+20 111 222 3333',
};

export const users: User[] = [
  currentUser,
  {
    id: '2',
    name: 'Sarah Williams',
    email: 'sarah@example.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face',
    role: 'Designer',
  },
  {
    id: '3',
    name: 'John Smith',
    email: 'john@example.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
    role: 'Developer',
  },
  {
    id: '4',
    name: 'Emma Davis',
    email: 'emma@example.com',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
    role: 'Designer',
  },
  {
    id: '5',
    name: 'Michael Brown',
    email: 'michael@example.com',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
    role: 'Developer',
  },
  {
    id: '6',
    name: 'Rachel Green',
    email: 'rachel@example.com',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face',
    role: 'Manager',
  },
  {
    id: '7',
    name: 'James Wilson',
    email: 'james@example.com',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop&crop=face',
    role: 'Developer',
  },
];

export const tasks: Task[] = [
  {
    id: '1',
    title: 'Design Login Screen',
    dueDate: '2026-06-28',
    priority: 'high',
    status: 'inProgress',
    progress: 70,
    assignees: [users[1], users[2], users[3]],
    category: 'Design',
    subtasks: 5,
  },
  {
    id: '2',
    title: 'API Integration',
    dueDate: '2026-05-03',
    priority: 'medium',
    status: 'inProgress',
    progress: 30,
    assignees: [users[4], users[5], users[6]],
    category: 'Development',
    subtasks: 8,
  },
  {
    id: '3',
    title: 'Write Documentation',
    dueDate: '2026-10-05',
    priority: 'low',
    status: 'inProgress',
    progress: 10,
    assignees: [users[0], users[1], users[5]],
    category: 'Documentation',
    subtasks: 3,
  },
  {
    id: '4',
    title: 'Create wireframes',
    dueDate: '2026-01-19',
    priority: 'high',
    status: 'completed',
    progress: 100,
    assignees: [users[1], users[2], users[3]],
    category: 'Design',
    subtasks: 4,
  },
  {
    id: '5',
    title: 'Design Dashboard UI',
    dueDate: '2026-01-23',
    priority: 'high',
    status: 'completed',
    progress: 100,
    assignees: [users[1], users[2], users[5]],
    category: 'Design',
    subtasks: 6,
  },
  {
    id: '6',
    title: 'Fix Critical Bug',
    dueDate: '2026-02-28',
    priority: 'high',
    status: 'overdue',
    progress: 50,
    assignees: [users[2], users[3], users[4]],
    category: 'Bug Fix',
    subtasks: 2,
  },
  {
    id: '7',
    title: 'Update privacy policy',
    dueDate: '2026-03-02',
    priority: 'medium',
    status: 'overdue',
    progress: 25,
    assignees: [users[4], users[5], users[6]],
    category: 'Legal',
    subtasks: 1,
  },
  {
    id: '8',
    title: 'Fix Landing Page Bugs',
    dueDate: '2026-03-22',
    priority: 'high',
    status: 'inProgress',
    progress: 20,
    assignees: [users[2], users[3]],
    category: 'Bug Fix',
    subtasks: 3,
  },
  {
    id: '9',
    title: 'Plan New Projects',
    dueDate: '2026-04-15',
    priority: 'medium',
    status: 'inProgress',
    progress: 60,
    assignees: [users[0], users[1]],
    category: 'Planning',
    subtasks: 5,
  },
];

export const projects: Project[] = [
  {
    id: '1',
    name: 'Food website project',
    dueDate: '2024-05-25',
    progress: 51,
    status: 'active',
    tasks: 15,
    members: [users[0], users[1], users[2], users[3], users[4], users[5]],
    tags: ['Design', 'Development'],
    color: '#4A7C9B',
    description: 'Marketing material almost ready',
  },
  {
    id: '2',
    name: 'Ridder share app project',
    dueDate: '2024-06-10',
    progress: 47,
    status: 'active',
    tasks: 22,
    members: [users[0], users[1], users[2], users[3], users[4], users[5]],
    tags: ['Marketing', 'On Hold'],
    color: '#6B9AB8',
    description: 'Marketing materials in progress',
  },
  {
    id: '3',
    name: 'Website Redesign',
    dueDate: '2024-05-25',
    progress: 60,
    status: 'active',
    tasks: 15,
    members: [users[0], users[1], users[2]],
    tags: ['Design', 'Development', 'Active'],
    color: '#4A7C9B',
    description: 'Marketing material almost ready',
  },
  {
    id: '4',
    name: 'Product Launch Campaign',
    dueDate: '2024-06-10',
    progress: 45,
    status: 'onHold',
    tasks: 22,
    members: [users[0], users[4], users[5]],
    tags: ['Marketing', 'On Hold'],
    color: '#FF9800',
    description: 'Marketing materials in progress',
  },
  {
    id: '5',
    name: 'Mobile App Development',
    dueDate: '2024-04-30',
    progress: 90,
    status: 'active',
    tasks: 30,
    members: [users[0], users[2], users[3], users[4]],
    tags: ['Development', 'Active'],
    color: '#4CAF50',
    description: 'SEO Optimization - Recent increase in organic traffic',
  },
];

export const teams: Team[] = [
  {
    id: '1',
    name: 'Design Team',
    description: 'UI/UX Designers working on user interface design',
    members: [users[0], users[1], users[3]],
    memberCount: 8,
    progress: 70,
    color: '#4A7C9B',
  },
  {
    id: '2',
    name: 'Development Team',
    description: 'Software engineers and developers',
    members: [users[0], users[2], users[4]],
    memberCount: 12,
    progress: 45,
    color: '#4CAF50',
  },
  {
    id: '3',
    name: 'Marketing Team',
    description: 'Marketing and growth team',
    members: [users[0], users[5], users[6]],
    memberCount: 6,
    progress: 30,
    color: '#FF9800',
  },
];

export const calendarEvents: CalendarEvent[] = [
  {
    id: '1',
    title: 'Team Meeting',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    date: '2024-04-17',
    assignees: [users[0], users[1], users[2]],
    color: '#4A7C9B',
    taskCount: 12,
    assignee: 'Team',
  },
  {
    id: '2',
    title: 'Dashboard UI Design Review',
    startTime: '11:30 AM',
    endTime: '12:30 PM',
    date: '2024-04-17',
    assignees: [users[0], users[1], users[2]],
    color: '#9C27B0',
    assignee: 'Mark',
  },
  {
    id: '3',
    title: 'Fix Login Page Bug',
    startTime: '2:00 PM',
    endTime: '3:00 PM',
    date: '2024-04-17',
    assignees: [users[0], users[1], users[2]],
    color: '#FF9800',
    assignee: 'Sarah',
  },
  {
    id: '4',
    title: 'Mobile App Testing',
    startTime: '3:30 PM',
    endTime: '4:30 PM',
    date: '2024-04-17',
    assignees: [users[0], users[2], users[4]],
    color: '#4CAF50',
    status: 'In progress',
  },
];

export const analyticsData: AnalyticsData = {
  totalTasks: 241,
  completed: 124,
  overdue: 32,
  overdued: 124,
  ongoing: 17,
  weeklyData: [
    { day: 'Mon', completed: 12, overdue: 5 },
    { day: 'Tue', completed: 22, overdue: 8 },
    { day: 'Wed', completed: 23, overdue: 10 },
    { day: 'Thu', completed: 33, overdue: 12 },
    { day: 'Fri', completed: 44, overdue: 20 },
    { day: 'Sat', completed: 40, overdue: 18 },
    { day: 'Sun', completed: 50, overdue: 30 },
  ],
};

export const weekDays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

export const calendarDays = [
  { day: 18, date: '2024-04-18' },
  { day: 19, date: '2024-04-19' },
  { day: 20, date: '2024-04-20' },
  { day: 17, date: '2024-04-17', isToday: true },
  { day: 18, date: '2024-04-18' },
  { day: 19, date: '2024-04-19' },
  { day: 20, date: '2024-04-20' },
];

export const homeDays = [
  { day: 'Fri', date: 11 },
  { day: 'Sat', date: 12 },
  { day: 'Sun', date: 14, isSelected: true },
  { day: 'Mon', date: 14 },
  { day: 'Tue', date: 15 },
];
